### ISSUE TITLE
Mudar a permissão para apache

### ISSUE THREAD

**Issue by ribafs** [dancodeweb/scripts_apache_mysql_php7#1]
Olá Dan!
Tudo bem meu caro?
Legal por compartilhar.

Apenas uma sugestão:
Acho prudente que as permissões fiquem assim:
Ao invés de
chmod 777 -R /var/www/html/

Usar
chmod 775 -R /var/www/html/

Assim fica com todos os direitos para o Apache e para o grupo. Os demais somente acesso.

Se for num desktop e quizer mais liberdade adicionar o usuário atual para o grupo do apache:
sudo adduser nome_user:www-data

**Comment by dancodeweb** [comment]
Opa, tudo bem?

Obrigado pela contribuição e dica.
